-- String Prefixes
Strings.INFO_TAG = "[INFO]: "
Strings.WARNING_TAG = "[WARN]: "
Strings.ERROR_TAG = "[ERROR]: "

-- Fragments
Strings.FRAG_COLON = ": "
Strings.FRAG_FAILED_VALIDATION = "Validation Failure: "
Strings.FRAG_BECAUSE = " Because: "
Strings.FRAG_PROVIDED_BY = " provided by "
Strings.FRAG_KEY_IS_IN_TABLE = "Key is in table: "
Strings.FRAG_FLESHED_OBJECT_EXISTS = "Fleshed Object exists: "
Strings.FRAG_MOD_ID = " mod with ID "
Strings.FRAG_ALREADY_REGISTERED = " is already registered."
Strings.FRAG_NO_ACTION_RESOURCES_FOUND = "No action resources found."
Strings.FRAG_SETTING_GOD_TO = "Setting God to "
Strings.FRAG_COULD_NOT_CAST = "Could not cast "
Strings.FRAG_TO_NUMBER = " to number."
-- Info
Strings.LOADED_REQUIRED_FILES = "Required Files loaded."

-- Warnings
Strings.WARN_UNFINISHED_API = "Using an Unfinished API. Proceed at your own risk."
Strings.WARN_GUID_NOT_DEFINED = " unknown - guid not defined"
Strings.WARN_UNNECESSARY_CALL = "Unnecessary call from Mod "

-- Errors
Strings.ERROR_INVALID_CLASS_PROVIDED =
"Invalid Class Supplied. Provide a UUID, or Insert the Parent Class into Globals.ClassUUIDs"
Strings.ERROR_DISABLED_API = "This API Call is not currently enabled."
Strings.ERROR_EMPTY_PAYLOAD = "Payload is empty."
Strings.ERROR_INVALID_PROGRESSION_TYPE = "Invalid String Type."
Strings.ERROR_INVALID_BOOLEAN_TYPE = "Unsupported Boolean key: "
Strings.ERROR_INVALID_LIST_TYPE = "Invalid List Type."
Strings.ERROR_LIST_NOT_FOUND = "Target list not found!"
Strings.ERROR_EMPTY_ARRAYS = "Arrays are both empty."
Strings.ERROR_MOD_NOT_LOADED = "Mod isn't loaded. Expected UUID: "
Strings.ERROR_PROGRESSION_EXISTS_IN_DICTIONARY = "Progression is already defined in Globals.Progressions"
Strings.ERROR_FEAT_EXISTS_IN_DICTIONARY = "Feat is already defined in Globals.Feats"
Strings.ERROR_ACTION_RESOURCE_EXISTS_IN_DICTIONARY = "Action Resource is already defined in Globals.ActionResources"
Strings.ERROR_ACTION_RESOURCE_GROUP_EXISTS_IN_DICTIONARY =
"Action Resource Group is already defined in Globals.ActionResourceGroups"
Strings.ERROR_LIST_EXISTS_IN_DICTIONARY_EQUIPMENT = "List is already defined in Globals.EquipmentLists."
Strings.ERROR_LIST_EXISTS_IN_DICTIONARY_ABILITY = "List is already defined in Globals.AbilityLists."
Strings.ERROR_LIST_EXISTS_IN_DICTIONARY_SKILL = "List is already defined in Globals.SkillLists."
Strings.ERROR_LIST_EXISTS_IN_DICTIONARY_SPELL = "List is already defined in Globals.SpellLists."
Strings.ERROR_LIST_EXISTS_IN_DICTIONARY_PASSIVE = "List is already defined in Globals.PassiveLists."
Strings.ERROR_PAYLOAD_MISSING_FIELD = "Payload is missing expected field "
Strings.ERROR_ACTION_RESOURCE_DOES_NOT_EXIST_IN_DICTIONARY = "Action Resource is not defined in Globals.ActionResources"
Strings.ERROR_ACTION_RESOURCE_GROUP_DOES_NOT_EXIST_IN_DICTIONARY =
"Action Resource Group is not defined in Globals.ActionResourceGroups"
Strings.ERROR_FEAT_DOES_NOT_EXIST_IN_DICTIONARY = "Feat is not defined in Globals.Feats"
Strings.ERROR_PROGRESSION_DOES_NOT_EXIST_IN_DICTIONARY = "Progression is not defined in Globals.Progressions"
Strings.ERROR_LIST_DOES_NOT_EXIST_IN_DICTIONARY_ABILITIES = "List is not defined in Globals.AbilityLists"
Strings.ERROR_LIST_DOES_NOT_EXIST_IN_DICTIONARY_EQUIPMENT = "List is not defined in Globals.EquipementLists"
Strings.ERROR_LIST_DOES_NOT_EXIST_IN_DICTIONARY_SKILL = "List is not defined in Globals.SkillLists"
Strings.ERROR_LIST_DOES_NOT_EXIST_IN_DICTIONARY_SPELL = "List is not defined in Globals.SpellLists"
Strings.ERROR_LIST_DOES_NOT_EXIST_IN_DICTIONARY_PASSIVE = "List is not defined in Globals.PassiveLists"
Strings.ERROR_TARGET_NOT_FOUND = "Target Object not found!"
Strings.ERROR_RACE_DATA_NOT_FOUND = "Race Data not found!"
Strings.ERROR_INVALID_ENTITY = "Invalid Entity"
